"""empty message

Revision ID: 200edd3062cc
Revises: 969a6fdff48a
Create Date: 2020-06-03 16:24:04.074211

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '200edd3062cc'
down_revision = '969a6fdff48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    probe_status = postgresql.ENUM('unchecked', 'tracked', 'discarded', name='probe_status')
    probe_status.create(op.get_bind())
    op.add_column('probes', sa.Column('device_id', sa.String(length=255), nullable=False))
    op.add_column('probes', sa.Column('probe_status', sa.Enum('unchecked', 'tracked', 'discarded', name='probe_status'), nullable=False))
    op.alter_column('probes', 'bssid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('probes', 'ssid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    probe_status = postgresql.ENUM('unchecked', 'tracked', 'discarded', name='probe_status')
    probe_status.drop(op.get_bind())
    op.alter_column('probes', 'ssid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('probes', 'bssid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('probes', 'probe_status')
    op.drop_column('probes', 'device_id')
    # ### end Alembic commands ###
