"""empty message

Revision ID: 44c7ba2d4f35
Revises: 5085e58cc331
Create Date: 2020-06-19 11:33:06.823004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c7ba2d4f35'
down_revision = '5085e58cc331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key('device_id_fk', 'locations', 'devices', ['device_id'], ['id'], onupdate="CASCADE", ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_id_fk', 'locations', type_='foreignkey')
    op.drop_column('locations', 'device_id')
    # ### end Alembic commands ###
