"""empty message

Revision ID: 5b99d4139b32
Revises: 44c7ba2d4f35
Create Date: 2020-06-19 12:00:13.716369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b99d4139b32"
down_revision = "44c7ba2d4f35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("probes", "device_id", new_column_name="esp_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("probes", "esp_id", new_column_name="device_id")
    # ### end Alembic commands ###
